name: 'icfp2015'
version: 0.0.1
description: icfp contest 2015

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any
  dart_to_js_script_rewriter: any
  http: any
  logging: any
  route: any
  args: any
  vector_math: any

transformers:
- dart_to_js_script_rewriter